### PR TITLE
Update packages.yml

### PR DESCRIPTION
**Pull request by rcaddell**
Fishtown has re-branded as dbt-labs.  This renames the dbt_utils package to match the name change used by other packages.

### CODE REVIEW

**Comment by chrismeier** [comment]
Would love to see this merged as it's causing issues with some of our other packages that have already been updated.

**Comment by tayloramurphy** [comment]
This is a read replica of https://github.com/gitlabhq/snowflake_spend - the merge request should be on the GitLab project.

**Comment by chrismeier** [comment]
> This is a read replica of https://gitlab.com/gitlab-data/snowflake_spend - the merge request should be on the GitLab project.

@tayloramurphy - it looks like the replica functionality might not be working here. It looks like the merge request went through in Gitlab, but the change isn't showing up here.

**Comment by tayloramurphy** [comment]
@chrismeier can you open an issue in the GitLab issue board? I no longer work at GitLab which probably broke the sync. Someone on the team will have to get it updated. Sorry about that!

**Comment by csh789** [comment]
Thanks for your submission. This change was made in the GitLab source repo [here](https://gitlab.com/gitlab-data/snowflake_spend/-/merge_requests/16) and released in v1.3.0.

**Pull request closed without merging**
